config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"
  resources :vehicles do
    resources :bookings, only: [:index, :new, :create]
  end
  resources :bookings, only: [:destroy]
  get "/my_vehicles", to: "vehicles#my_vehicles"
  get "/mis_reservas", to: "bookings#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :vehicle
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :vehicles, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_one_attached :photo
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy

  has_one_attached :photo
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :photo])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
    @vehicle = Vehicle.find(params[:vehicle_id])
  end

  def create
    @vehicle = Vehicle.find(params[:vehicle_id])
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.vehicle = @vehicle
    @vehicle.update(take: true)
    if @booking.save!
      redirect_to vehicle_bookings_path(@vehicle), notice: 'Booking was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.vehicle.update(take: false)
    @booking.destroy
    redirect_to mis_reservas_path, notice: 'Booking was successfully destroyed.'
  end

  private
  def booking_params
    params.require(:booking).permit(:name, :start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  def index
    @vehicles = Vehicle.where(take: false)
    if params[:vehicle_type].present?
      @vehicles = @vehicles.where(vehicle_type: params[:vehicle_type])
    end
    if params[:query].present?
      sql_subquery = <<~SQL
      brand @@ :query
      OR model @@ :query
      OR ubication @@ :query
      SQL
      @vehicles = @vehicles.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  # GET /vehicles/1
  def show
    @vehicle = set_vehicle
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
    @vehicle = set_vehicle
  end

  # POST /vehicles
  def create
    @vehicle = Vehicle.new(vehicle_params)
    @vehicle.user = current_user

    if @vehicle.save
      redirect_to @vehicle, notice: 'Vehicle was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /vehicles/1
  def update
    @vehicle = Vehicle.find(params[:id])
    if @vehicle.update(vehicle_params)
      redirect_to @vehicle, notice: 'Vehicle was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /vehicles/1
  def destroy
    @vehicle.destroy
    redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.'
  end

  def my_vehicles
    @vehicles = current_user.vehicles
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_vehicle
    @vehicle = Vehicle.find(params[:id])
  end

    # Only allow a trusted parameter "white list" through.
  def vehicle_params
    params.require(:vehicle).permit(:brand, :model, :year, :color, :mileage, :vehicle_type, :description, :name, :ubication, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<div class="container-1">
<% @bookings.each do |booking| %>
    <div class="card-vehicle">
      <%= cl_image_tag booking.vehicle.photo.key, height: 300, width: 400, crop: :fill, class: "vehicle-photo" if booking.vehicle.photo.attached? %>
      <h2><%= booking.vehicle.brand %></h2>
      <p><%= booking.vehicle.model %></p>
      <p><%= booking.vehicle.year %></p>
      <p><%= booking.name %></p>
      <%= link_to 'Borrar', booking_path(booking), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "button mx-3 text-decoration-none" %>
    </div>
<% end %>
</div>

app/views/bookings/new.html.erb
<h1>Complete</h1>
<div class="d-flex justify-content-around">
<div class="container-2">
<%= simple_form_for [@vehicle, @booking] do |form| %>
  <div class="field">
    <%= form.input :start_date, html5: true %>
  </div>
  <div class="field">
    <%= form.input :end_date, html5: true%>
  </div>
  <div class="field">
    <%= form.input :name %>
  </div>
  <div class="actions">
    <%= form.submit "Rent"%>
  </div>
<% end %>
</div>

<div class="container-2">
  <div class="card-vehicle">
    <h1><%= @vehicle.brand %></h1>
    <p><%= @vehicle.model %></p>
    <p><%= @vehicle.year %></p>
    <p><%= @vehicle.description %></p>
  </div>
</div>
</div>

<%= link_to 'Back', vehicles_path, class: "btn-back" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnb</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/flashes" %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container">
  <div class="jumbotron text-center">
    <h1 style="margin: revert">Bienvenido!</h1>
    <p style="margin: revert">Encuentra el vehiculo perfecto para tu aventura.</p>
  </div>

  <div class="row">
    <div class="col-md-4">
        <div class="card">
            <%= image_tag "foto1.jpg", class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title">Descubre lugares increíbles</h5>
                <p class="card-text">Explora una amplia variedad de alojamientos únicos en todo el mundo.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <%= image_tag "foto2.jpg", class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title">Reserva fácilmente</h5>
                <p class="card-text">Reserva de manera segura y sin complicaciones, con opciones de cancelación flexibles.</p>
            </div>
        </div>
    </div>
    <div class="col-md-4">
        <div class="card">
            <%= image_tag "foto3.jpg", class: "card-img-top" %>
            <div class="card-body">
                <h5 class="card-title">Únete a nuestra comunidad</h5>
                <p class="card-text">Conéctate con viajeros de todo el mundo y comparte tus experiencias.</p>
            </div>
        </div>
    </div>
  </div>

</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Header con el logo y el login -->
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-dark">
  <div class="container-fluid">
    <%= link_to  root_path, class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ms-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", root_path, class: "nav-link text-white" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link text-white" %>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <% if current_user.photo.attached? %>
                <%= cl_image_tag current_user.photo.key, class: "avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag "avatar.png", class: "avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Mis vehiculos", my_vehicles_path, class: "dropdown-item" %>
              <%= link_to "Mis reservas", mis_reservas_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link text-white" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

<!-- Barra de búsqueda -->
<% if current_page?(root_path) || user_signed_in? %>

  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon bg-light">
    <div class="container">

        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to vehicles_path, class: "nav-link"  do %>
              <i class="fa-solid fa-border-all" style="color: #170745;"></i> Todos
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to vehicles_path(vehicle_type: "car"), class: "nav-link"  do %>
              <i class="fa-solid fa-car-side" style="color: #170745;"></i> Autos
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to vehicles_path(vehicle_type: "bike"), class: "nav-link" do %>
              <i class="fa-solid fa-bicycle"></i> Bicicletas
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to vehicles_path(vehicle_type: "motorcycle"), class: "nav-link" do %>
              <i class="fa-solid fa-motorcycle"></i> Motos
            <% end %>
          </li>

          <li class="nav-item">
            <%= link_to vehicles_path(vehicle_type: "van"), class: "nav-link" do %>
              <i class="fa-solid fa-van-shuttle"></i> Vans
            <% end %>
          </li>
        </ul>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <%= form_with url: vehicles_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
          %>
        <%= submit_tag "Search", name: "", class: "btn-search" %>
        <% end %>

      </div>
    </div>
  </div>

<% end %>

app/views/vehicles/edit.html.erb
<%# edit the vehicle information %>


<%# Path: app/views/vehicles/edit.html.erb %>
<h1>Editar vehiculo</h1>
<div class="container-2">

  <%= form_with model: @vehicle, local: true do |form| %>
    <div class="field">
      <%= form.label :brand %>
      <%= form.text_field :brand %>
    </div>

    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model %>
    </div>

    <div class="field">
      <%= form.label :year %>
      <%= form.text_field :year %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :ubication %>
      <%= form.text_field :ubication %>
    </div>

    <div class="field">
      <%= form.label :vehicle_type %>
      <%= form.select :vehicle_type, options_for_select({ 'Automóvil' => 'car', 'Bicicleta' => 'bike', 'Motocicleta' => 'motorcycle', 'Furgoneta' => 'van' }) %>
    </div>

    <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo, as: :field %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
</div>

<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<h1>Catalogo</h1>
<div class="head-vehicles">
  <h2>Nuestros vehiculos</h2>
  <%=link_to 'New Vehicle', new_vehicle_path, class: "btn-new", style: "margin-bottom: 6px" %>
</div>

<div class="container-1">
  <% @vehicles.each do |vehicle| %>
    <div class="card-vehicle">
      <%= cl_image_tag vehicle.photo.key, height: 300, width: 400, crop: :fill, class: "vehicle-photo" if vehicle.photo.attached? %>
      <h2 style="margin-top: inherit;"><%= vehicle.brand %></h2>
      <p>Modelo: <%= vehicle.model %></p>
      <p>Año: <%= vehicle.year %></p>
      <p>Dueño: <%= vehicle.name %></p>
      <p>Ubicación: <%= vehicle.ubication %></p>
      <p>Precio: <%= vehicle.price %></p>

      <%= link_to 'Ver', vehicle, class: "btn-ver" %>
    </div>
  <% end %>
</div>

app/views/vehicles/my_vehicles.html.erb
<div class="head-vehicles">
<h2 style="margin-top: 5px">Mis vehiculos</h2>
<%=link_to 'New Vehicle', new_vehicle_path, class: "btn-new", style: "margin-bottom: auto; margin-top: auto" %>
</div>

<div class="container-1">
<% @vehicles.each do |vehicle| %>
  <div class="card-vehicle">
    <%= cl_image_tag vehicle.photo.key, height: 300, width: 400, crop: :fill, class: "vehicle-photo" if vehicle.photo.attached? %>
    <h2 style="margin-top: inherit;"><%= vehicle.brand %></h2>
    <p><%= vehicle.model %></p>
    <p><%= vehicle.year %></p>
    <div class="d-flex justify-content-beetwen">
      <%= link_to 'Ver', vehicle, class: "button mx-3 text-decoration-none" %>
      <%= link_to 'Editar', edit_vehicle_path(vehicle), class: "button mx-3 text-decoration-none" %>
      <%= link_to 'Borrar', vehicle_path(vehicle), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?' }, class: "button mx-3 text-decoration-none" %>
    </div>
  </div>
<% end %>
</div>

app/views/vehicles/new.html.erb
<h1>create a new vehicle</h1>
<div class="container-2">
  <%= form_with model: @vehicle, local: true do |form| %>
    <div class="field">
      <%= form.label :brand %>
      <%= form.text_field :brand %>
    </div>

    <div class="field">
      <%= form.label :model %>
      <%= form.text_field :model %>
    </div>

    <div class="field">
      <%= form.label :year %>
      <%= form.text_field :year %>
    </div>

    <div class="field">
      <%= form.label :description %>
      <%= form.text_field :description %>
    </div>
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name %>
    </div>
    <div class="field">
      <%= form.label :ubication %>
      <%= form.text_field :ubication %>
    </div>

    <div class="field">
    <%= form.label :vehicle_type %>
    <%= form.select :vehicle_type, options_for_select({ 'Automóvil' => 'car', 'Bicicleta' => 'bike', 'Motocicleta' => 'motorcycle', 'Furgoneta' => 'van' }) %>
    </div>

    <div class="field">
      <%= form.label :photo %>
      <%= form.file_field :photo %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>

</div>

<div><%= link_to 'Back', vehicles_path , class: "btn-back"%></div>
<br>
<div><%= link_to 'Mis publicaciones', my_vehicles_path, class: "btn-back"%></div>

app/views/vehicles/rent.html.erb
<h1>Complete</h1>
<div class="d-flex justify-content-around">
<div class="container-2">
<%= form_with model: @rent, local: true do |form| %>
  <div class="field">
    <%= form.label :start_date %>
    <%= form.date_field :start_date %>
  </div>
  <div class="field">
    <%= form.label :end_date %>
    <%= form.date_field :end_date %>
  </div>
  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>
  <div class="field">
    <%= form.label "Comment" %>
    <%= form.text_field "Comment" %>
  </div>
  <div class="actions">
    <%= form.submit "Rent"%>
  </div>
<% end %>
</div>

<div class="container-2">
  <div class="card-vehicle">
    <h1><%= @vehicle.brand %></h1>
    <p><%= @vehicle.model %></p>
    <p><%= @vehicle.year %></p>
    <p><%= @vehicle.description %></p>
  </div>
</div>
</div>

<%= link_to 'Back', vehicles_path, class:"btn btn-primary" %>

app/views/vehicles/show.html.erb
<div class="container-1">
  <div class="card-vehicle">
    <%# <% @vehicle.photos.each do |photo| %>
    <%= cl_image_tag @vehicle.photo.key, height: 300, width: 400, crop: :fill, class: "vehicle-photo" if @vehicle.photo.attached? %>
    <%# <% end %>
    <h2 style="margin-top: inherit;"><%= @vehicle.brand %></h2>
    <p>Modelo: <%= @vehicle.model %></p>
    <p>Año: <%= @vehicle.year %></p>
    <p>Dueño: <%= @vehicle.name %></p>
    <p>ubicación: <%= @vehicle.ubication %></p>
    <p>Detalles: <%= @vehicle.description %></p>
  </div>
</div>

<%= link_to "back", vehicles_path, class: "btn-back"%>

<%= link_to "Rent", new_vehicle_booking_path(@vehicle), class: "btn-back" %>